# Generated by Django 4.0.6 on 2022-07-20 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date changed'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date changed'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
